project:
  type: book

book:
  title: "Rust Espacial"
  subtitle: "Procesos y Operaciones Espaciales Avanzadas"
  # affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2025-10-05"
  language: "es"
  # number-sections: 3
  page-footer:
    left: "Copyright 2024, Denis Berroeta"
  chapters:
    - index.qmd
    - intro.qmd
    - install.qmd
    - part: "Conceptos Básicos"
      chapters:
        - variables.qmd
        - flow_control.qmd
        - scope.qmd
        - funcions.qmd
        - macros.qmd
        - iterators.qmd
        - closures.qmd
        - errors.qmd
        - struct.qmd
        - traits.qmd
        - impl.qmd
        - ownership.qmd
    - part: "Optimización"
      chapters:
        - optimization.qmd
        - paralelization.qmd
    - part: "Rust Espacial"
      chapters:
        - spatial_chapter.qmd
        - geotypes.qmd
        - formats.qmd
        - geos.qmd
        - osm.qmd
        - geocoding.qmd
        - routing.qmd
        - geohash.qmd
        - h3o.qmd
        #- rtree.qmd
        #- raster.qmd
    - part: "Integración con R"
      chapters:
        - integration.qmd
        - h3o-R.qmd
    - part: "Integracción con DDBB"
      chapters:
        - sqlite.qmd
        - duckdb.qmd
    #- part: "Práctica"
     # chapters:
     #   - scrapping.qmd
    - part: "Proyectos"
      chapters:
        - project_1.qmd
        - project_2.qmd
    - part: "Anexos"
      chapters:
        - functional.qmd
        #- languages.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
    code-block-bg: "#f0f0f0"
    code-block-border-left: "#31BAE9"

execute:
  warning: false
  eval: false

editor: source
always_allow_html: true



